# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc20b44525d370206a929b22fff6df8acb3af020d415dde9fa4103c1c0be66fe6fa71144829834882e2c929dcd28e766f5729ccb51b5b85d9dac389e32e8057

test:
  secret_key_base: 0186dc6df81b2bdc71b669090c0a96f79ef4e599d15c07ec5f668fdc6c0d0c4e4451b267a525a347a1471781853563cdf56de2d15d121819682a77c91b2fc436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
